services:
  flask-app:
    container_name: flask-app
    image: shdhkim/flask-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - milvus
    environment:
      - FLASK_APP=app2.py       # Flask 진입점 명시
      - FLASK_ENV=production    # 프로덕션 모드로 실행
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    restart: always

  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - MILVUS_LOG_LEVEL=info
      - MILVUS_DB_PATH=/var/lib/milvus/db
    restart: always

volumes:
  milvus_data: