services:
  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - MILVUS_LOG_LEVEL=info
      - MILVUS_DB_PATH=/var/lib/milvus/db
      - MILVUS_DEPLOY_MODE=standalone
      - LD_PRELOAD=
    command: milvus run standalone
    restart: always
    networks:
      - app_network

  flask-app:
    container_name: flask-app
    image: shdhkim/flask-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - milvus
    environment:
      - FLASK_APP=app2.py
      - FLASK_ENV=production
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    restart: always
    networks:
      - app_network

volumes:
  milvus_data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/docker/volumes/milvus_data/_data
      o: bind

networks:
  app_network:
    driver: bridge